# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_Data',
            fields=[
                ('account', models.IntegerField(primary_key=True, serialize=False)),
                ('Access_token', models.CharField(max_length=100, unique=True)),
                ('Access_secret', models.CharField(max_length=100, unique=True)),
                ('Screen_Name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
            ],
        ),
    ]
