# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_Bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteKeywords',
            fields=[
                ('Fav_key_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Fav_keywords', models.CharField(max_length=50, null=True, unique=True)),
                ('num_limits', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
