# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_Bot', '0005_res_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Black_List_Names',
            fields=[
                ('Name_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_users', models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('status', models.CharField(default='manual', max_length=10)),
            ],
        ),
    ]
