# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_Bot', '0007_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('Job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('initial_time', models.DateTimeField(blank=True, null=True)),
                ('final_time', models.DateTimeField(blank=True, null=True)),
                ('Account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter_Bot.Accounts_Data')),
            ],
            options={
                'ordering': ['initial_time', 'final_time'],
            },
        ),
    ]
