# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_Bot', '0008_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetsData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tweet_id', models.IntegerField(null=True)),
                ('tweet_content', models.CharField(max_length=1000, null=True)),
                ('Name', models.CharField(max_length=1000, null=True)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('jobs', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter_Bot.Jobs')),
            ],
        ),
    ]
