# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_Bot', '0018_auto_20180612_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeTweetsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter_Bot.Accounts_Data')),
            ],
        ),
        migrations.AddField(
            model_name='tweetsdata',
            name='Account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter_Bot.Accounts_Data'),
        ),
        migrations.AddField(
            model_name='liketweetscontent',
            name='TweetContent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter_Bot.TweetsData'),
        ),
    ]
