# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 09:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_Bot', '0021_auto_20180620_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav_keywords',
            name='num_limits',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fav_keywords',
            name='Account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_id', to='Twitter_Bot.Accounts_Data'),
        ),
        migrations.AlterField(
            model_name='fav_keywords',
            name='keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter_Bot.FavouriteKeywords'),
        ),
    ]
