# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-07 06:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_Bot', '0023_remove_favouritekeywords_num_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritekeywords',
            name='num_limits',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
